In [83]:
# TEST SQUARE DIVERGENCE
import numpy as np

array = np.array((
    [ [ -0.304384, 0.210328, 0.982011,],  [ 0.661298, 0.433782, 0.565086,],  [ -0.591405, 0.256926, 0.157736,],  [ -0.936899, -0.453914, -0.932886,],  [ 0.977504, 0.915959, 0.518743,],  [ 0.512501, -0.388489, 0.658924,],  [ 0.543513, 0.823473, 0.108267,],  [ -0.352375, -0.371234, 0.672551,], ],
    [ [ -0.440565, -0.581481, -0.949183,],  [ -0.913519, 0.478972, 0.08921,],  [ -0.646882, -0.138656, -0.384915,],  [ 0.729862, 0.785668, 0.716136,],  [ 0.0979396, 0.0710889, 0.791305,],  [ -0.539747, 0.465981, -0.266117,],  [ -0.622262, -0.358842, 0.949627,],  [ 0.37889, -0.00284511, 0.181893,], ],
    [ [ -0.91718, 0.954475, -0.140185,],  [ -0.0936148, 0.61727, 0.463685,],  [ -0.846517, 0.589575, 0.981185,],  [ 0.778305, 0.971377, -0.0702169,],  [ -0.135521, 0.306429, 0.150047,],  [ -0.158441, -0.924684, 0.834507,],  [ -0.44859, 0.551754, -0.678843,],  [ 0.690132, -0.956479, 0.454522,], ],
    [ [ -0.857239, 0.380942, 0.4959,],  [ 0.593557, -0.0784699, -0.842905,],  [ -0.698931, -0.934852, -0.0558315,],  [ -0.360253, -0.779439, -0.0394176,],  [ -0.492211, -0.58179, -0.149445,],  [ 0.276998, -0.499781, 0.174453,],  [ 0.0311509, -0.445848, 0.631663,],  [ 0.35328, -0.428376, 0.282657,], ],
    [ [ 0.608543, -0.214997, 0.543219,],  [ -0.116876, -0.331271, 0.321621,],  [ -0.51511, 0.550538, 0.88682,],  [ 0.786801, -0.228518, -0.693925,],  [ -0.803433, 0.703807, 0.884749,],  [ -0.027597, 0.177747, -0.60649,],  [ 0.716826, -0.305666, 0.664083,],  [ -0.757956, -0.970075, -0.056208,], ],
    [ [ -0.688061, -0.23806, 0.92306,],  [ -0.131474, 0.320348, 0.0933882,],  [ -0.424282, -0.916123, 0.72722,],  [ 0.392153, 0.920452, 0.0288527,],  [ 0.92778, -0.809468, -0.732356,],  [ -0.710573, -0.599609, 0.374911,],  [ -0.872487, 0.115481, 0.891608,],  [ -0.735598, 0.799348, 0.650357,], ],
    [ [ 0.54782, -0.791487, -0.51526,],  [ 0.0214934, -0.760192, -0.539434,],  [ -0.266748, 0.769908, -0.15074,],  [ 0.518345, -0.175319, -0.585365,],  [ -0.223419, 0.998181, 0.432691,],  [ 0.228529, 0.893999, -0.564551,],  [ -0.40935, 0.0472237, -0.310746,],  [ -0.705108, -0.744941, -0.219204,], ],
    [ [ -0.161015, -0.174891, 0.605065,],  [ -0.669789, 0.854316, 0.489494,],  [ 0.931298, 0.332682, -0.605672,],  [ 0.476084, -0.455692, -0.820758,],  [ -0.472426, -0.0696015, 0.206745,],  [ 0.7581, -0.618464, -0.520509,],  [ -0.200064, -0.483292, -0.681869,],  [ -0.164035, -0.9332, -0.296827,], ],))

answer = np.array((
    [ [0.965682, -0.791809, -2.34812], [-2.21839, 0.0451909, 1.04797], [0.907209, -0.395582, -1.1574], [2.2599, 1.23958, 3.6433], [-2.37941, -0.84487, -1.23628], [0.496014, 0.85447, -1.74826], [-0.9269, -1.18231, 2.33068], [0.895888, 0.368389, -2.00457],],
    [ [-0.472954, 2.32776, 2.26431], [0.739592, 0.093107, -0.501297], [1.11011, 1.12381, 3.1833], [-2.00867, -1.05387, -3.52891], [-0.00576484, 1.08021, -1.05251], [0.555172, -2.24513, 3.50828], [1.08367, 2.09291, -4.06111], [-1.00115, -1.32202, 2.39176],],
    [ [0.823565, -2.10949, 0.201563], [-1.57647, -0.834038, -0.95105], [2.37772, -2.25266, -1.88288], [-2.53865, -1.93653, 1.21291], [0.890905, -1.12356, 1.41159], [-0.267227, 1.81557, -3.08965], [1.42887, -1.9082, 3.87166], [-1.13872, 1.48174, -1.755],],
    [ [1.4508, -0.0224066, -1.89536], [-2.74329, 0.442939, 1.38678], [1.63117, 3.00982, 0.845942], [-0.470635, 2.30174, -1.92745], [0.901165, 2.17382, 1.32814], [-1.01505, 0.252626, 0.155422], [0.567976, 1.13778, -0.669007], [-0.322129, -1.0698, -0.19942],],
    [ [-0.725419, 0.572876, 1.49705], [0.327185, 0.904421, -0.829948], [1.70015, -2.95205, -1.52853], [-2.89215, 0.598047, 2.57108], [2.36607, -2.79887, -4.15502], [-0.031413, -1.45488, 3.41187], [-2.21921, 0.280966, -1.12516], [1.47478, 2.31112, 0.817904],],
    [ [0.556587, -0.530363, -2.04639], [-0.849396, -1.73216, 0.874131], [1.10924, 3.15269, 0.63724], [-0.28081, -2.24474, -2.07614], [-2.17398, 3.32092, 4.37777], [1.47644, 2.27096, -2.85838], [0.298802, -0.489405, 0.216147], [-0.136888, -3.31371, -0.373771],],
    [ [-0.526326, 1.17002, 1.92582], [0.238085, 2.69505, -0.336535], [1.07333, -2.12326, -1.22012], [-1.52686, 0.815397, 1.9988], [1.19371, -2.87543, -2.09506], [-1.08983, -3.00607, 0.00709528], [0.342123, -0.462258, -0.082371], [0.295757, 1.35603, 1.16306],],
    [ [-0.508774, -0.616596, -0.696462], [2.10986, -1.61451, -1.36829], [-2.0563, 0.437226, 1.3147], [-0.493296, 0.280373, 0.224533], [2.17904, 1.06778, -0.757515], [-2.18869, 1.51246, 0.31209], [0.994194, 0.530515, 0.454859], [-0.0360296, 0.188259, -0.307419],]))

off_hori = 1 
off_vert = 1

v11 = 1 * array[off_vert + 1, off_hori + 0, 0]
v12 = - 2 * array[off_vert + 1, off_hori + 1, 0]
v13 = 1 * array[off_vert + 1, off_hori + 2, 0]
v1 = v11 + v12 + v13

v1_ = array[off_vert + 1, off_hori:off_hori + 3, 0] * np.array((1, -2, 1))
v2_ = array[off_vert:off_vert + 3, off_hori + 1, 1] * np.array((1, -2, 1))
v3_ = array[off_vert:off_vert + 3, off_hori:off_hori + 3, 2] * np.array(([[0, 1, -1], [1, -2, 1], [-1, 1, 0]]))

# print(v1, v1_.sum())
print(v1_.sum())
print(v2_.sum())
print(v3_.sum())
print(v1_.sum(),  v2_.sum(), v3_.sum(), answer[off_vert + 1, off_hori + 1])# (x, y) = (off_hori + 1, off_vert + 1)

2.3777242
-2.252658
-1.8828794
2.3777242 -2.252658 -1.8828794 [ 2.37772 -2.25266 -1.88288]


In [55]:
# TEST SQUARE SYM GRAD
import numpy as np

input = np.array((
    [  0.178534,   0.615847,   0.548382,   0.661969,   -0.284038,   0.178962,   -0.183141,   -0.0588983, ], 
    [  0.0964996,   -0.132255,   -0.816964,   -0.711638,   -0.495698,   0.807031,   -0.226431,   0.37782, ], 
    [  0.0158523,   0.430576,   0.698128,   -0.565823,   0.214378,   -0.955061,   0.294268,   -0.231532, ], 
    [  0.640774,   -0.51025,   0.220094,   -0.88018,   0.821654,   -0.462173,   0.261039,   -0.719364, ], 
    [  -0.352053,   -0.956811,   0.882068,   0.922225,   -0.164514,   -0.984531,   0.992848,   0.791273, ], 
    [  0.919904,   0.834012,   -0.768772,   -0.74467,   0.325553,   -0.430516,   0.324497,   -0.180627, ], 
    [  0.199442,   0.0158983,   -0.795959,   0.314654,   0.396959,   -0.310385,   -0.634522,   -0.407265, ], 
    [  -0.906201,   -0.516987,   0.994946,   0.0496141,   -0.136865,   -0.297127,   0.181053,   0.953578, ], 
))

answer = np.array((
    [ [ 0.437314, -0.0820341, 0.35528,],  [ -0.504779, -0.748103, -0.733534,],  [ 0.181052, -1.36535, -0.503656,],  [ -1.05959, -1.37361, -0.954268,],  [ 1.40901, -0.21166, 1.62495,],  [ -0.825103, 0.628069, 0.477626,],  [ 0.486347, -0.0432893, -0.547115,],  [ -0.124243, 0.436718, 0.538906,], ],
    [ [ -0.228755, 0.00138688, -0.746716,],  [ -0.455953, 1.31093, 0.0262359,],  [ 0.790035, 2.88044, 0.943999,],  [ 0.110614, 1.51942, -0.20733,],  [ 1.08679, 0.921736, 1.40399,],  [ -2.33619, -2.39016, -3.14353,],  [ 1.63771, 0.563988, 2.7628,],  [ -0.60425, -1.04607, -1.56677,],],
    [ [ 0.414724, 0.705569, 1.2684,],  [ -0.147173, -1.50366, -0.613489,],  [ -1.5315, -1.99313, -0.906484,],  [ 2.04415, -0.460172, 0.727938,],  [ -1.94964, -0.102799, -1.55053,],  [ 2.41877, 2.25498, 2.1684,],  [ -1.77513, -0.553929, -1.65617,],  [ 0.5258, 0.12152, 0.154749,], ], 
 [ [ -1.15102, -1.61775, -2.55858,],  [ 1.88137, 0.494267, 1.00906,],  [ -1.83062, 1.14001, 1.27221,],  [ 2.80211, 2.11676, 2.06206,],  [ -2.98566, -1.59344, -2.90296,],  [ 2.00704, -1.01525, -0.0623073,],  [ -1.70361, 0.765038, 0.799564,],  [ 0.980403, 1.99847, 1.26666,], ],   
 [ [ -0.604758, 2.26478, 1.81822,],  [ 2.44364, 2.23738, 1.6274,],  [ -1.79872, -2.31281, -2.30123,],  [ -1.1269, -3.4693, -2.80463,],  [ 0.266722, 1.47623, 2.62077,],  [ 2.7974, 1.07637, 1.31811,],  [ -2.17895, -1.40016, -0.443538,],  [ 0.201575, -2.48254, -1.81419,], ],       
 [ [ -0.0858929, -1.99242, -0.201598,],  [ -1.51689, -2.60894, -3.53931,],  [ 1.62688, 1.62365, 0.77487,],  [ 1.04612, 2.72622, 3.24347,],  [ -1.82629, -0.418661, -0.923971,],  [ 1.51108, -0.433884, -1.17364,],  [ -1.26014, -0.290668, -1.3827,],  [ 0.505124, 0.745262, 1.70428,], ],                                                                                                                                         
 [ [ -0.183543, -0.38518, -1.20329,],  [ -0.628314, 0.285228, 1.36368,],  [ 1.92247, 1.81809, 3.4103,],  [ -1.02831, -1.32437, -3.04386,],  [ -0.789648, -0.60523, -0.220059,],  [ 0.383206, -0.106874, -0.532068,],  [ 0.551394, 1.77459, 1.5347,],  [ -0.227257, 1.58748, 0.771907,], ],                                                                                                                                         
 [ [ 0.389214, 1.10564, 1.47896,],  [ 1.12272, 0.532886, 1.93458,],  [ -2.45726, -1.7909, -3.56788,],  [ 0.758852, 0.26504, 0.676547,],  [ 0.0262176, 0.533824, 0.733561,],  [ 0.638442, -0.0132573, 0.962579,],  [ 0.294345, -0.815575, 0.0670887,],  [ -0.772525, -1.36084, -2.13337,], ],                                                                                                                                       
))

off_hori = 2
off_vert = 2

v1_ = input[off_vert + 1, off_hori:off_hori + 3] * np.array([1, -2, 1])
v2_ = input[off_vert:off_vert + 3, off_hori + 1] * np.array([1, -2, 1])
v3_ = input[off_vert:off_vert + 3, off_hori:off_hori + 3] * np.array([[0, 1, -1], [1, -2, 1], [-1, 1, 0]])

print(v1_.sum(), v2_.sum(), v3_.sum())
print(answer[off_vert + 1, off_hori + 1])


2.802108 2.116762 2.062064
[ 2.80211  2.11676  2.06206]


In [155]:

input = np.array((
    [[0.43, 0.82, 0.35, 0.50, 0.74, 0.73, 0.18, 1.33],
     [0.50, 1.05, 1.37, 0.95, 1.40, 0.21, 1.62, 0.82],
     [0.62, 0.47, 0.48, 0.04, 0.54, 0.12, 0.43, 0.53],
     [0.18, 0.38, 1.20, 0.62, 0.28, 1.36, 1.92, 1.81],
     [0.80, 3.41, 1.02, 1.32, 3.04, 0.78, 0.60, 0.22],
     [0.38, 0.10, 0.53, 0.55, 1.77, 1.53, 0.22, 1.58],
     [0.38, 1.10, 1.47, 1.12, 0.53, 1.93, 2.45, 1.79],
     [3.56, 0.75, 0.26, 0.67, 0.02, 0.53, 0.73, 0.63]]
))

v_bar = np.array((
    [ [ 0.44, -0.8, 0.35,],  [ -0.5, -0.7, -0.7,],  [ 0.18, -1.3, -0.5,],  [ -1.0, -1.3, -0.9,],
      [ 1.40, -0.2, 1.62,],  [ -0.8, 0.62, 0.46,],  [ 0.48, -0.4, -0.5,],  [ -0.1, 0.43, 0.53,], ],
    [ [ -0.5, 0.08, -0.7,],  [ -0.4, 1.31, 0.02,],  [ 0.79, 2.88, 0.94,],  [ 0.11, 1.51, -0.2,],
      [ 1.08, 0.92, 1.40,],  [ -2.3, -2.3, -3.3,],  [ 1.63, 0.56, 2.76,],  [ -0.6, -1.0, -1.5,],],
    [ [ 0.44, 0.70, 1.26,],  [ -0.1, -1.5, -0.6,],  [ -1.5, -1.9, -0.9,],  [ 2.04, -0.4, 0.72,],
      [ -1.9, -0.1, -1.5,],  [ 2.41, 2.25, 2.16,],  [ -1.7, -0.5, -1.6,],  [ 0.52, 0.12, 0.15,], ], 
    [ [ -1.2, -1.6, -2.5,],  [ 1.88, 0.49, 1.00,],  [ -1.8, 1.14, 1.27,],  [ 2.80, 2.11, 2.06,],
      [ -2.9, -1.5, -2.9,],  [ 2.00, -1.5, -0.3,],  [ -1.7, 0.76, 0.79,],  [ 0.98, 1.99, 1.26,], ],
    [ [ -0.58, 2.2, 1.81,],  [ 2.44, 2.23, 1.62,],  [ -1.7, -2.3, -2.3,],  [ -1.1, -3.4, -2.8,],
      [ 0.26, 1.47, 2.62,],  [ 2.79, 1.07, 1.31,],  [ -2.1, -1.4, -0.4,],  [ 0.20, -2.4, -1.8,], ],
    [ [ -0.9, -1.9, -0.2,],  [ -1.5, -2.6, -3.5,],  [ 1.62, 1.62, 0.77,],  [ 1.04, 2.72, 3.24,],
      [ -1.8, -0.4, -0.9,],  [ 1.51, -0.4, -1.1,],  [ -1.2, -0.2, -1.3,],  [ 0.50, 0.74, 1.70,], ],
    [ [ -0.4, -0.3, -1.2,],  [ -0.6, 0.28, 1.36,],  [ 1.92, 1.81, 3.41,],  [ -1.0, -1.3, -3.0,],
      [ -0.7, -0.6, -0.2,],  [ 0.38, -0.1, -0.5,],  [ 0.54, 1.77, 1.53,],  [ -0.2, 1.58, 0.77,], ],
    [ [ 0.34, 1.10, 1.47,],  [ 1.12, 0.53, 1.93,],  [ -2.4, -1.9, -3.6,],  [ 0.75, 0.26, 0.67,],
      [ 0.02, 0.53, 0.71,],  [ 0.63, -0.3, 0.96,],  [ 0.29, -0.8, 0.06,],  [ -0.7, -1.3, -2.1,], ],
))


def square_sym_grad(src):
    rows = src.shape[0]
    cols = src.shape[1]
    
    src_zero = np.zeros((rows + 2, cols + 2))
    src_zero[1:-1, 1:-1] = src

    src_edge = np.zeros((src.shape[0] + 2, src.shape[1] + 2))
    src_edge[1:-1, 1:-1] = src
    src_edge[1:-1, 0] = src[:, 0]
    src_edge[1:-1, -1] = src[:, -1]
    src_edge[0, 1:-1] = src[0, :]
    src_edge[-1, 1:-1] = src[-1, :]
    
    dst = np.zeros((rows, cols, 3))

    for y in range(0, rows):
        for x in range(0, cols):
            dst[y, x, 0] = np.sum(np.array(([1, -2, 1])) * src_edge[y + 1, x:x + 3])
            dst[y, x, 1] = np.sum(np.array(([1, -2, 1])) * src_edge[y:y+3, x + 1])
            dst[y, x, 2] = (np.sum(np.array(([[0, 1, -1], [1, -2, 1], [-1, 1, 0]])) * src_zero[y:y + 3, x:x + 3])) * 0.5
    return dst


def square_div(src):
    rows = src.shape[0]
    cols = src.shape[1]
    
    src0 = np.zeros((rows + 2, cols + 2))
    src1 = np.zeros((rows + 2, cols + 2))
    src2 = np.zeros((rows + 2, cols + 2))

    src0[1:-1, 1:-1] = src[:, :, 0]
    src1[1:-1, 1:-1] = src[:, :, 1]
    src2[1:-1, 1:-1] = src[:, :, 2]

    src0[1:-1, 0] = src[:, 0, 0]
    src0[1:-1, -1] = src[:, -1, 0]
    src0[0, 1:-1] = src[0, :, 0]
    src0[-1, 1:-1] = src[-1, :, 0]
    
    src1[1:-1, 0] = src[:, 0, 1]
    src1[1:-1, -1] = src[:, -1, 1]
    src1[0, 1:-1] = src[0, :, 1]
    src1[-1, 1:-1] = src[-1, :, 1]

    dst = np.zeros((rows, cols))
    
    for y in range(0, rows):
        for x in range(0, cols):
            dst[y, x] = np.sum(np.array(([1, -2, 1])) * src0[y + 1, x:x + 3]) \
                + np.sum(np.array(([1, -2, 1])) * src1[y:y+3, x + 1]) \
                + np.sum(np.array(([[0, 1, -1], [1, -2, 1], [-1, 1, 0]])) * src2[y:y + 3, x:x + 3])
    return dst

tau = 1 / 64

v_hat = v_bar + tau * square_sym_grad(input - square_div(v_bar))



# print(input)
# print(square_div(v_bar))
# print(input - square_div(v_bar))
# print(v_bar + tau * square_sym_grad(input - square_div(v_bar)))



In [136]:

def sym_grad(src):
    rows = src.shape[0]
    cols = src.shape[1]

    dst = np.zeros((rows, cols, 3))

    dst[:, 1:, 0] = src[:, 1:, 0] - src[:, :-1, 0]
    dst[:, 0, 0] = src[:, 0, 0]
    dst[:, -1, 0] = -src[:, -2, 0]
    
    dst[1:, :, 1] = src[1:, :, 1] - src[:-1, :, 1]
    dst[0, :, 1] = src[0, :, 1]
    dst[-1, :, 1] = -src[-2, :, 1]

    tmp = np.zeros((rows, cols, 2))
    tmp[:, 1:, 0] = src[:, 1:, 1] - src[:, :-1, 1]
    tmp[:, 0, 0] = src[:, 0, 1]
    tmp[:, -1, 0] = -src[:, -2, 1]
    
    tmp[1:, :, 1] = src[1:, :, 0] - src[:-1, :, 0]
    tmp[0, :, 1] = src[0, :, 0]
    tmp[-1, :, 1] = -src[-2, :, 0]

    dst[:, :, 2] = (tmp[:, :, 0] + tmp[:, :, 1]) * 0.5

    return dst


eta_bar = np.zeros((8, 8, 2))
eta_bar[:, :, 0] = np.array((
    [[  2.59,  -4.7,   -2.2, -7.7,  6.30,  4.67,  -6.7,  8.55], 
     [  -3.7,  6.64,   14.1, 2.18,  1.25,  -2.5,  24.1,  -1.0], 
     [  1.42,  -7.6,   -1.1, 7.75,  -2.5,  27.7,  -1.8,  4.93], 
     [  -1.7,  10.5,   4.42, 2.97,  -2.0,  2.17,  3.04,  1.73], 
     [  1.38,  24.4,   -1.9, -4.2,  2.01,  13.9,  -9.5,  -1.4], 
     [  -0.1,  -2.5,   7.21, 3.39,  -1.1,  4.37,  -1.5,  12.8], 
     [  -7.7,  5.33,   27.7, -5.3,  1.28,  0.57,  14.8,  5.24], 
     [  7.75,  13.3,   -2.3, 1.14,  -0.7,  4.46,  -0.9,  -8.2]]
))

eta_bar[:, :, 1] = np.array((
    [[  2.59,  -4.7,  -2.29,  -7.6,  6.3,  4.67,  -6.97,  8.44], 
     [  2.66,  -4.5,  -1.27,  -7.2,  6.9,  4.15,  -5.53,  7.49], 
     [  2.78,  -5.1,  -2.16,  -8.1,  6.1,  4.06,  -6.72,  7.23], 
     [  2.34,  -5.2,  -1.44,  -7.5,  5.8,  5.31,  -5.23,  8.48], 
     [  2.96,  -2.1,  -1.62,  -6.8,  8.6,  4.72,  -6.55,  6.89], 
     [  2.54,  -5.5,  -2.11,  -7.6,  7.3,  5.47,  -6.93,  8.25], 
     [  2.54,  -4.5,  -1.17,  -7.0,  6.0,  5.87,  -4.73,  8.46], 
     [  5.72,  -4.8,  -2.38,  -7.5,  5.5,  4.47,  -6.42,  7.31]]
))

print(eta_bar)
print(sym_grad(eta_bar))

[[[  2.59   2.59]
  [ -4.7   -4.7 ]
  [ -2.2   -2.29]
  [ -7.7   -7.6 ]
  [  6.3    6.3 ]
  [  4.67   4.67]
  [ -6.7   -6.97]
  [  8.55   8.44]]

 [[ -3.7    2.66]
  [  6.64  -4.5 ]
  [ 14.1   -1.27]
  [  2.18  -7.2 ]
  [  1.25   6.9 ]
  [ -2.5    4.15]
  [ 24.1   -5.53]
  [ -1.     7.49]]

 [[  1.42   2.78]
  [ -7.6   -5.1 ]
  [ -1.1   -2.16]
  [  7.75  -8.1 ]
  [ -2.5    6.1 ]
  [ 27.7    4.06]
  [ -1.8   -6.72]
  [  4.93   7.23]]

 [[ -1.7    2.34]
  [ 10.5   -5.2 ]
  [  4.42  -1.44]
  [  2.97  -7.5 ]
  [ -2.     5.8 ]
  [  2.17   5.31]
  [  3.04  -5.23]
  [  1.73   8.48]]

 [[  1.38   2.96]
  [ 24.4   -2.1 ]
  [ -1.9   -1.62]
  [ -4.2   -6.8 ]
  [  2.01   8.6 ]
  [ 13.9    4.72]
  [ -9.5   -6.55]
  [ -1.4    6.89]]

 [[ -0.1    2.54]
  [ -2.5   -5.5 ]
  [  7.21  -2.11]
  [  3.39  -7.6 ]
  [ -1.1    7.3 ]
  [  4.37   5.47]
  [ -1.5   -6.93]
  [ 12.8    8.25]]

 [[ -7.7    2.54]
  [  5.33  -4.5 ]
  [ 27.7   -1.17]
  [ -5.3   -7.  ]
  [  1.28   6.  ]
  [  0.57   5.87]
  [ 14.8   -4.73

In [171]:
answer = np.array((
  [ [  2.59, 2.59, 2.59,],  [  -7.29, -4.7, -5.995,],  [  2.5, -2.29, 0.105,],  [  -5.5, -7.6, -6.505,],  [  14, 6.3, 10.1,],  [  -1.63, 4.67, 1.52,],  [  -11.37, -6.97, -9.17,],  [  6.7, 8.44, 7.76,], ],
 [ [  -3.7, 0.0700002, -1.815,],  [  10.34, 0.2, 2.09,],  [  7.46, 1.02, 9.765,],  [  -11.92, 0.4, 1.975,],  [  -0.93, 0.6, 4.525,],  [  -3.75, -0.52, -4.96,],  [  26.6, 1.44, 10.56,],  [  -24.1, -0.95, -2.01,], ],
 [ [  1.42, 0.12, 3.95,],  [  -9.02, -0.6, -11.06,],  [  6.5, -0.89, -6.13,],  [  8.85, -0.900001, -0.185,],  [  -10.25, -0.8, 5.225,],  [  30.2, -0.0900002, 14.08,],  [  -29.5, -1.19, -18.34,],  [  1.8, -0.26, 6.325,], ],
 [ [  -1.7, -0.44, -0.39,],  [  12.2, -0.0999999, 5.28,],  [  -6.08, 0.72, 4.64,],  [  -1.45, 0.6, -5.42,],  [  -4.97, -0.3, 6.9,],  [  4.17, 1.25, -13.01,],  [  0.87, 1.49, -2.85,],  [  -3.04, 1.25, 1.015,], ],
 [ [  1.38, 0.62, 3.02,],  [  23.02, 3.1, 4.42,],  [  -26.3, -0.18, -2.92,],  [  -2.3, 0.7, -6.175,],  [  6.21, 2.8, 9.705,],  [  11.89, -0.59, 3.925,],  [  -23.4, -1.32, -11.905,],  [  9.5, -1.59, 1.71,], ],
 [ [  -0.1, -0.42, 0.53,],  [  -2.4, -3.4, -17.47,],  [  9.71, -0.49, 6.25,],  [  -3.82, -0.8, 1.05,],  [  -4.49, -1.3, 5.895,],  [  5.47, 0.75, -5.68,],  [  -5.87, -0.38, -2.2,],  [  1.5, 1.36, 10.565,], ],
 [ [  -7.7, 0, -2.53,],  [  13.03, 1, 0.395,],  [  22.37, 0.94, 11.91,],  [  -33, 0.6, -7.26,],  [  6.58, -1.3, 7.69,],  [  -0.71, 0.4, -1.965,],  [  14.23, 2.2, 2.85,],  [  -14.8, 0.21, -1.415,], ],
 [ [  7.75, -2.54, 6.71,],  [  5.55, 4.5, -7.925,],  [  -15.6, 1.17, -12.64,],  [  3.44, 7, 0.0900002,],  [  -1.84, -6, 5.86,],  [  5.16, -5.87, -0.8,],  [  -5.36, 4.73, -12.845,],  [  0.9, -8.46, 0.59,], ],
))

sym_grad_eta_bar = sym_grad(eta_bar)

# print(np.abs((answer[:, :, :] - sym_grad_eta_bar[:, :, :])) < 1.0e-5)

# print(eta_bar[2, :, 0])
# # print(eta_bar[1, :, 0])
# print(answer[2, : , :])
# print(sym_grad_eta_bar[2, :, :])

answer = np.array((
    [ [  2.91484, 1.70156, 2.8382,],  [  -7.63594, -5.22156, -6.54211,],  [  2.55703, -3.33297, -0.397734,],  [  -6.19766, -8.74609, -7.34742,],  [  15.1562, 6.23984, 11.7002,],  [  -2.58641, 4.74906, 1.54867,],  [  -10.4742, -6.87187, -9.03352,],  [  6.36609, 8.5575, 7.82219,], ],
    [ [  -4.04828, 0.449219, -2.27617,],  [  9.90578, 1.10891, 1.93258,],  [  7.94531, 3.17781, 10.5322,],  [  -11.4186, 1.84313, 2.04406,],  [  -0.760469, 0.939531, 5.32078,],  [  -4.48656, -1.37797, -7.06961,],  [  26.7961, 0.814531, 12.1205,],  [  -24.1233, -1.37297, -2.87781,], ],
    [ [  1.57828, 0.154687, 4.76602,],  [  -8.96328, -1.59422, -11.4124,],  [  5.49, -2.01188, -6.73898,],  [  10.2016, -1.14922, 0.233593,],  [  -11.1911, -0.632188, 4.19055,],  [  31.2433, 0.867969, 15.3367,],  [  -30.0936, -0.657031, -19.0958,],  [  1.94484, -0.267031, 6.23867,], ],
    [ [  -2.44406, -1.11594, -2.28641,],  [  13.5289, 0.324531, 6.16898,],  [  -7.495, 1.19703, 5.58859,],  [  0.326094, 1.73172, -3.76055,],  [  -6.71859, -0.936718, 4.60641,],  [  5.75797, 0.316406, -13.1992,],  [  -0.668281, 1.70703, -2.35047,],  [  -2.22703, 2.69312, 2.10023,], ],
    [ [  1.00406, 2.16313, 4.61039,],  [  24.5931, 4.33391, 5.46062,],  [  -27.4378, -1.73641, -4.82922,],  [  -2.6025, -1.0875, -8.02031,],  [  5.67547, 3.04391, 11.3637,],  [  14.4102, 0.155156, 5.24172,],  [  -25.1775, -2.55391, -12.352,],  [  9.745, -3.18516, 0.328047,], ],
    [ [  -1.38703, -2.24422, -0.0213281,],  [  -3.00375, -4.74172, -20.0883,],  [  11.1986, 1.04984, 7.17602,],  [  -3.86859, 0.162188, 2.98656,],  [  -5.29063, -0.924063, 5.75117,],  [  6.44203, 0.44, -6.87078,],  [  -6.43891, -0.139843, -3.0525,],  [  1.61828, 1.58578, 11.8034,], ],
    [ [  -7.89562, 0.05375, -3.3132,],  [  12.5684, 0.925313, 1.61328,],  [  23.1258, 1.59906, 14.2391,],  [  -32.7633, 0.786406, -8.97789,],  [  5.45359, -2.17125, 7.02437,],  [  -0.1, 0.420156, -2.185,],  [  14.4052, 3.3225, 3.96648,],  [  -14.8541, 1.69766, -0.571875,], ],
    [ [  8.17734, -1.68219, 8.06094,],  [  5.96281, 4.90484, -6.52,],  [  -16.7634, 0.1075, -15.211,],  [  3.35703, 6.65938, 0.13586,],  [  -1.52312, -5.43906, 6.72398,],  [  5.62891, -6.23078, -0.0300001,],  [  -5.10797, 4.16859, -12.731,],  [  0.318437, -9.54891, -1.34523,], ],
))


shrink_image = sym_grad_eta_bar + v_hat

# print(np.abs(answer - shrink_image)[:, :, :] < 1.0e-3)

# print(shrink_image[1, : ,:])
# print(answer[1, :, :])

alpha0 = 0.1

shrink_abs = np.abs(shrink_image)
q = np.where((shrink_abs - alpha0) > 0,  (shrink_abs - alpha0) * shrink_image / shrink_abs, 0)

answer = np.array((
    [ [  2.81484, 1.60156, 2.7382,],  [  -7.53594, -5.12156, -6.44211,],  [  2.45703, -3.23297, -0.297734,],  [  -6.09766, -8.64609, -7.24742,],  [  15.0562, 6.13984, 11.6002,],  [  -2.48641, 4.64906, 1.44867,],  [  -10.3742, -6.77187, -8.93352,],  [  6.26609, 8.4575, 7.72219,], ],
    [ [  -3.94828, 0.349219, -2.17617,],  [  9.80578, 1.00891, 1.83258,],  [  7.84531, 3.07781, 10.4322,],  [  -11.3186, 1.74313, 1.94406,],  [  -0.660469, 0.839531, 5.22078,],  [  -4.38656, -1.27797, -6.96961,],  [  26.6961, 0.714531, 12.0205,],  [  -24.0233, -1.27297, -2.77781,], ],
    [ [  1.47828, 0.0546874, 4.66602,],  [  -8.86328, -1.49422, -11.3124,],  [  5.39, -1.91188, -6.63898,],  [  10.1016, -1.04922, 0.133593,],  [  -11.0911, -0.532188, 4.09055,],  [  31.1433, 0.767969, 15.2367,],  [  -29.9936, -0.557031, -18.9958,],  [  1.84484, -0.167031, 6.13867,], ],
    [ [  -2.34406, -1.01594, -2.18641,],  [  13.4289, 0.224531, 6.06898,],  [  -7.395, 1.09703, 5.48859,],  [  0.226094, 1.63172, -3.66055,],  [  -6.61859, -0.836718, 4.50641,],  [  5.65797, 0.216406, -13.0992,],  [  -0.568281, 1.60703, -2.25047,],  [  -2.12703, 2.59312, 2.00023,], ],
    [ [  0.904062, 2.06313, 4.51039,],  [  24.4931, 4.23391, 5.36062,],  [  -27.3378, -1.63641, -4.72922,],  [  -2.5025, -0.9875, -7.92031,],  [  5.57547, 2.94391, 11.2637,],  [  14.3102, 0.0551561, 5.14172,],  [  -25.0775, -2.45391, -12.252,],  [  9.645, -3.08516, 0.228047,], ],
    [ [  -1.28703, -2.14422, 0,],  [  -2.90375, -4.64172, -19.9883,],  [  11.0986, 0.949844, 7.07602,],  [  -3.76859, 0.0621878, 2.88656,],  [  -5.19063, -0.824063, 5.65117,],  [  6.34203, 0.34, -6.77078,],  [  -6.33891, -0.0398434, -2.9525,],  [  1.51828, 1.48578, 11.7034,], ],
    [ [  -7.79562, 0, -3.2132,],  [  12.4684, 0.825312, 1.51328,],  [  23.0258, 1.49906, 14.1391,],  [  -32.6633, 0.686406, -8.87789,],  [  5.35359, -2.07125, 6.92438,],  [  -2.23517e-08, 0.320156, -2.085,],  [  14.3052, 3.2225, 3.86648,],  [  -14.7541, 1.59766, -0.471875,], ],
    [ [  8.07734, -1.58219, 7.96094,],  [  5.86281, 4.80484, -6.42,],  [  -16.6634, 0.00750008, -15.111,],  [  3.25703, 6.55937, 0.0358595,],  [  -1.42312, -5.33906, 6.62398,],  [  5.52891, -6.13078, 0,],  [  -5.00797, 4.06859, -12.631,],  [  0.218437, -9.44891, -1.24523,], ],

))

# print(np.abs(q - answer)[:, :, :] < 1.0e-3)

# print(q[5, :, :])
# print(answer[5, :, :])


In [184]:
answer = np.array((
    [ [  0.0999999, 0.0999999, 0.0999999,],  [  -0.0999999, -0.0999999, -0.0999999,],  [  0.0999999, -0.0999999, -0.1,],  [  -0.0999999, -0.1, -0.0999999,],  [  0.1, 0.0999999, 0.0999994,],  [  -0.0999999, 0.0999999, 0.1,],  [  -0.1, -0.0999999, -0.1,],  [  0.0999994, 0.1, 0.0999999,] , ],
    [ [  -0.0999999, 0.1, -0.0999999,],  [  0.1, 0.1, 0.1,],  [  0.0999999, 0.0999999, 0.1,],  [  -0.1, 0.1, 0.1,],  [  -0.1, 0.1, 0.0999999,],  [  -0.0999999, -0.1, -0.0999999,],  [  0.1, 0.1, 0.1,],  [  -0.1, -0.1, -0.0999999,], ],
    [ [  0.1, 0.1, 0.0999999,],  [  -0.1, -0.0999999, -0.100001,],  [  0.0999999, -0.1, -0.0999999,],  [  0.1, -0.1, 0.1,],  [  -0.1, -0.1, 0.0999999,],  [  0.1, 0.1, 0.1,],  [  -0.1, -0.1, -0.1,],  [  0.1, -0.1, 0.1,], ],
    [ [  -0.0999999, -0.1, -0.0999999,],  [  0.0999994, 0.1, 0.0999999,],  [  -0.0999999, 0.1, 0.0999999,],  [  0.1, 0.1, -0.0999999,],  [  -0.0999999, -0.1, 0.0999999,],  [  0.0999994, 0.1, -0.1,],  [  -0.1, 0.1, -0.0999999,],  [  -0.0999999, 0.0999999, 0.0999999,], ],
    [ [  0.1, 0.0999999, 0.0999999,],  [  0.1, 0.0999999, 0.0999999,],  [  -0.1, -0.1, -0.0999999,],  [  -0.0999999, -0.1, -0.0999999,],  [  0.0999999, 0.1, 0.1,],  [  0.1, 0.1, 0.0999999,],  [  -0.1, -0.0999999, -0.100001,],  [  0.1, -0.0999997, 0.1,], ],
    [ [  -0.1, -0.0999999, -0.0213281,],  [  -0.0999997, -0.0999999, -0.1,],  [  0.1, 0.1, 0.0999999,],  [  -0.0999999, 0.1, 0.0999999,],  [  -0.0999999, -0.1, 0.0999999,],  [  0.0999999, 0.1, -0.0999999,],  [  -0.0999999, -0.1, -0.0999997,],  [  0.1, 0.1, 0.1,], ],
    [ [  -0.0999999, 0.05375, -0.0999999,],  [  0.1, 0.1, 0.1,],  [  0.1, 0.1, 0.1,],  [  -0.0999985, 0.1, -0.1,],  [  0.0999999, -0.0999999, 0.0999999,],  [  -0.1, 0.1, -0.0999999,],  [  0.1, 0.0999999, 0.0999999,],  [  -0.1, 0.1, -0.1,], ],
    [ [  0.1, -0.1, 0.0999994,],  [  0.0999999, 0.0999999, -0.0999999,],  [  -0.1, 0.1, -0.1,],  [  0.0999997, 0.1, 0.1,],  [  -0.1, -0.0999999, 0.0999999,],  [  0.0999999, -0.0999999, -0.0300001,],  [  -0.0999999, 0.0999999, -0.0999994,],  [  0.1, -0.1, -0.1,], ],
))

def divergence(src):
    rows = src.shape[0]
    cols = src.shape[1]
    
    dst = np.zeros((rows, cols, 2))
    
    tmp = np.zeros((rows, cols, 4))
    tmp[:, :-1, 0] = src[:, 1:, 0] - src[:, :-1, 0]
    tmp[:-1, :, 1] = src[1:, :, 1] - src[:-1, :, 1]
    tmp[:-1, :, 2] = src[1:, :, 2] - src[:-1, :, 2]
    tmp[:, :-1, 3] = src[:, 1:, 2] - src[:, :-1, 2]

    dst[:, :, 0] = tmp[:, :, 0] + tmp[:, :, 2]
    dst[:, :, 1] = tmp[:, :, 1] + tmp[:, :, 3]

    return dst

tmp = shrink_image - q
# print(tmp)
# print((tmp - answer) < 1.0e-4)

answer = np.array((
    [ [  -0.4, -0.2,],  [  0.4, 0.2,],  [  5.66244e-07, 0.2,],  [  0.4, 0.4,],  [  -0.2, 6.55651e-07,],  [  -0.2, -0.4,],  [  0.400001, 0.4,],  [  -0.2, -0.2,], ],
    [ [  0.4, 0.2,],  [  -0.200002, -0.2,],  [  -0.400001, -0.2,],  [  3.27826e-07, -0.2,],  [  1.19209e-07, -0.4,],  [  0.400001, 0.4,],  [  -0.400002, -0.4,],  [  0.2, 2.98023e-08,], ],
    [ [  -0.4, -0.400001,],  [  0.400002, 0.200001,],  [  0.2, 0.4,],  [  -0.400001, 0.2,],  [  0.200001, 4.76837e-07,],  [  -0.400002, -0.200001,],  [  0.200001, 0.400001,],  [  -4.76837e-07, 0.2,], ],
    [ [  0.399999, 0.4,],  [  -0.199999, -1.04308e-07,],  [  8.9407e-08, -0.4,],  [  -0.2, -2.38419e-07,],  [  0.2, -1.19209e-07,],  [  8.34465e-07, 4.76837e-07,],  [  -1.3113e-06, -1.19209e-07,],  [  8.9407e-08, -0.2,], ],
    [ [  -0.121328, -0.2,],  [  -0.400001, -0.4,],  [  0.2, 0.2,],  [  0.4, 0.4,],  [  0, -0.200001,],  [  -0.400001, -0.200001,],  [  0.200002, 0.200001,],  [  3.8743e-07, 0.2,], ],
    [ [  -0.0786715, 0.0750776,],  [  0.4, 0.4,],  [  -0.2, 0,],  [  -0.2, 1.49012e-08,],  [  0.2, -0.2,],  [  -0.2, 2.08616e-07,],  [  0.399999, 0.4,],  [  -0.2, -1.19209e-07,], ],
    [ [  0.4, 0.0462499,],  [  -0.2, 2.38419e-07,],  [  -0.4, -0.200001,],  [  0.399999, 0.200001,],  [  -0.2, -0.2,],  [  0.27, -5.96046e-08,],  [  -0.4, -0.2,],  [  -2.98023e-08, -0.2,], ],
    [ [  -4.76837e-07, -0.199999,],  [  -0.2, -4.76837e-07,],  [  0.2, 0.2,],  [  -0.2, -9.68575e-08,],  [  0.2, -0.13,],  [  -0.2, -0.0699993,],  [  0.2, -5.96046e-07,],  [  0, 0,], ],
))

tmp = divergence(tmp)

# print(np.abs((tmp - answer)) < 1.0e-4)

answer = np.array((
    [ [  2.53375, 2.55875,],  [  -4.64375, -4.66875,],  [  -2.19375, -2.25875,],  [  -7.64375, -7.54375,],  [  6.26875, 6.29375,],  [  4.63875, 4.61375,],  [  -6.64375, -6.91375,],  [  8.51875, 8.40875,], ],
    [ [  -3.64375, 2.67875,],  [  6.60875, -4.51875,],  [  14.0437, -1.28875,],  [  2.17375, -7.21875,],  [  1.24375, 6.84375,],  [  -2.44375, 4.19375,],  [  24.0437, -5.57375,],  [  -0.96875, 7.48375,], ],
    [ [  1.36375, 2.72375,],  [  -7.54375, -5.06875,],  [  -1.06875, -2.10375,],  [  7.69375, -8.06875,],  [  -2.46875, 6.09375,],  [  27.6437, 4.02875,],  [  -1.76875, -6.66375,],  [  4.92375, 7.24875,], ],
    [ [  -1.64375, 2.38375,],  [  10.4688, -5.19375,],  [  4.41375, -1.48375,],  [  2.93875, -7.49375,],  [  -1.96875, 5.79375,],  [  2.16375, 5.30375,],  [  3.03375, -5.22375,],  [  1.72375, 8.44875,], ],
    [ [  1.35858, 2.92875,],  [  24.3438, -2.14375,],  [  -1.86875, -1.58875,],  [  -4.14375, -6.74375,],  [  2.00375, 8.56875,],  [  13.8437, 4.68875,],  [  -9.46875, -6.51875,],  [  -1.39375, 6.90875,], ],
    [ [  -0.103584, 2.54313,],  [  -2.44375, -5.44375,],  [  7.17875, -2.10375,],  [  3.35875, -7.59375,],  [  -1.06875, 7.26875,],  [  4.33875, 5.46375,],  [  -1.44375, -6.87375,],  [  12.7688, 8.24375,], ],
    [ [  -7.64375, 2.53953,],  [  5.29875, -4.49375,],  [  27.6437, -1.18875,],  [  -5.24375, -6.96875,],  [  1.24875, 5.96875,],  [  0.5975, 5.86375,],  [  14.7437, -4.74875,],  [  5.23375, 8.42875,], ],
    [ [  7.74375, 5.68875,],  [  13.2688, -4.79375,],  [  -2.26875, -2.34875,],  [  1.10875, -7.49375,],  [  -0.66875, 5.4775,],  [  4.42875, 4.455,],  [  -0.86875, -6.41375,],  [  -8.19375, 7.30375,], ],
))

sigma = 0.125
alpha1 = 0.05
lamb = sigma * alpha1

eta1 = eta_bar + sigma * tmp
abs_eta1 = np.abs(eta1)

eta1 = np.where(abs_eta1 - lamb > 0, (abs_eta1 - lamb) * eta1 / abs_eta1, 0)

# print((eta1 - answer)[:, :, :] < 1.0e-4)
# print(eta1[1, :, :])
# print(answer[1, :, :])


In [190]:
# nesterov acceleration
import math
t0 = 1
t1 = 0.5 + math.sqrt(1.25)
t2 = (1 + math.sqrt(1 + 4 * t1 * t1)) * 0.5
scale = t0 / t2

eta0 = np.array((
    [ [  -0.577999, -0.422623,],  [  0.976901, 0.773407,],  [  0.64835, 0.817624,],  [  -0.192355, -0.911331,],  [  -0.738172, -0.458732,],  [  0.0939006, 0.187666,],  [  0.109043, 0.689236,],  [  -0.0102813, -0.797914,], ],
    [ [  -0.537532, -0.305609,],  [  -0.36778, 0.729513,],  [  0.919491, -0.117589,],  [  -0.315258, -0.548793,],  [  0.436175, 0.791732,],  [  0.644343, -0.525998,],  [  -0.450293, -0.0720651,],  [  0.802465, -0.96863,], ],
    [ [  0.23163, -0.997831,],  [  -0.551111, -0.528437,],  [  0.550473, -0.192107,],  [  -0.749596, -0.467025,],  [  0.716188, 0.970752,],  [  -0.571702, -0.591953,],  [  -0.959735, -0.266169,],  [  0.500261, -0.112573,], ],
    [ [  -0.00788701, -0.556601,],  [  -0.799969, 0.915841,],  [  0.534539, 0.000149012,],  [  0.505385, 0.00827813,],  [  -0.868654, 0.538881,],  [  0.980808, 0.433686,],  [  0.969587, -0.147971,],  [  -0.955267, 0.824541,], ],
    [ [  0.0685481, 0.0884428,],  [  0.457563, 0.258594,],  [  0.192072, 0.155591,],  [  -0.98802, 0.351068,],  [  0.401535, 0.603917,],  [  0.0276294, 0.367454,],  [  -0.208112, 0.261129,],  [  0.791157, 0.96721,], ],
    [ [  -0.107206, 0.19213,],  [  -0.869886, -0.165716,],  [  0.814577, 0.598662,],  [  -0.285215, 0.387593,],  [  0.268975, 0.668703,],  [  0.890991, 0.881173,],  [  -0.121105, 0.580611,],  [  0.335097, -0.0198268,], ],
    [ [  0.770157, 0.0232509,],  [  0.777669, 0.277535,],  [  0.537593, -0.669293,],  [  -0.812729, 0.455588,],  [  -0.925211, -0.0296549,],  [  -0.410516, 0.452625,],  [  -0.735559, -0.548496,],  [  -0.568833, -0.371892,], ],
    [ [  -0.393294, -0.0869011,],  [  -0.547428, -0.626412,],  [  -0.100307, 0.144158,],  [  0.859541, 0.310373,],  [  0.445797, 0.505042,],  [  0.239461, 0.627706,],  [  -0.144108, -0.0314332,],  [  -0.29701, 0.153345,], ],
))


answer = np.array((
    [ [  3.95236, 3.91792,],  [  -7.20613, -7.14976,],  [  -3.48943, -3.66123,],  [  -11.0407, -10.5674,],  [  9.46311, 9.37212,],  [  6.71069, 6.63154,],  [  -9.72226, -10.3798,],  [  12.407, 12.6059,], ],
    [ [  -5.05983, 4.03928,],  [  9.78926, -6.91136,],  [  20.0269, -1.82267,],  [  3.30846, -10.2595,],  [  1.61191, 9.60279,],  [  -3.85157, 6.34542,],  [  35.2103, -8.0819,],  [  -1.77622, 11.3371,], ],
    [ [  1.87987, 4.42037,],  [  -10.7316, -7.13862,],  [  -1.80693, -2.97524,],  [  11.543, -11.5343,],  [  -3.92072, 8.42926,],  [  40.5068, 6.13527,],  [  -2.13757, -9.58032,],  [  6.94036, 10.6047,], ],
    [ [  -2.38952, 3.72422,],  [  15.606, -7.97903,],  [  6.18223, -2.16024,],  [  4.04809, -10.9138,],  [  -2.47027, 8.18938,],  [  2.70304, 7.52395,],  [  3.97477, -7.53773,],  [  2.94508, 11.9245,], ],
    [ [  1.94669, 4.22361,],  [  35.2331, -3.23895,],  [  -2.80825, -2.38397,],  [  -5.58241, -9.97818,],  [  2.73418, 12.1998,],  [  20.1423, 6.65877,],  [  -13.6906, -9.60961,],  [  -2.38982, 9.61742,], ],
    [ [  -0.101933, 3.61493,],  [  -3.16125, -7.84994,],  [  10.0801, -3.33574,],  [  5.01999, -11.2323,],  [  -1.6786, 10.2776,],  [  5.91054, 7.55289,],  [  -2.04673, -10.2721,],  [  18.4371, 12.011,], ],
    [ [  -11.4795, 3.68667,],  [  7.35985, -6.66892,],  [  40.0011, -1.42556,],  [  -7.26379, -10.3534,],  [  2.23983, 8.70334,],  [  1.05704, 8.33061,],  [  21.8006, -6.66359,],  [  7.87907, 12.4408,], ],
    [ [  11.4533, 8.32179,],  [  19.5674, -6.69358,],  [  -3.25731, -3.48523,],  [  1.22236, -11.0515,],  [  -1.17686, 7.74438,],  [  6.33859, 6.19981,],  [  -1.1991, -9.32336,],  [  -11.7938, 10.5635,], ],
))

eta_bar = eta1 + scale * (eta1 - eta0)

# print(np.abs(eta_bar - answer) < 1.0e-3)



In [193]:
# update_v1

answer = np.array((
    [ [  0.0437503, 0.0687501, 0.0562501,],  [  0.0125008, -0.0687499, -0.0406246,],  [  0.0499997, -0.0687499, -0.096875,],  [  -0.0499997, -0.0437498, -0.0593743,],  [  0.0125008, 0.09375, 0.0531244,],  [  -0.1, 0.0437498, 0.0593749,],  [  -0.0125008, -0.0437493, -0.015625,],  [  0.0437498, 0.0687504, 0.0562491,], ],
    [ [  -0.0437503, 0.15, -0.0343751,],  [  0.0124998, 0.0499998, 0.0374991,],  [  0.0749998, 0.0499998, 0.0687494,],  [  -0.0500002, 0.0249993, 0.06875,],  [  -0.1, 0.0499998, 0.0937505,],  [  -0.0374999, 3.57628e-07, -0.0062499,],  [  -0.0125008, -8.34465e-07, 9.53674e-07,],  [  -0.0437489, -0.0749999, -0.0468748,], ],
    [ [  0.0437499, 0.0249997, 0.015625,],  [  0.0124998, -0.0499997, -0.0124998,],  [  0.0749998, -0.025, -0.0437503,],  [  0.0125008, -0.0499998, 0.0625004,],  [  -0.0125008, -0.0499998, 0.1,],  [  0.0124989, 0.0249997, 0.031249,],  [  -0.0124989, 3.57628e-07, -0.0125008,],  [  0.0687499, -0.0749999, 0.0531254,], ],
    [ [  -0.0437498, 1.19209e-07, -0.0218749,],  [  0.0124998, 0.0749999, 0.037499,],  [  -0.0749998, 2.38419e-07, 0.0562501,],  [  0.0749997, 0.0749999, -0.0625,],  [  -0.0374994, -0.1, 0.09375,],  [  0.0624995, 0.125, -0.0750008,],  [  -0.1, 0.0499998, -0.1125,],  [  -0.09375, 0.0499997, 0.096875,], ],
    [ [  0.0785841, 0.025, 0.045542,],  [  0.0651665, 0.05, 0.0812502,],  [  -0.0124989, -0.025, -0.0437498,],  [  -0.0749998, -0.0499998, -0.0437503,],  [  0.0374999, 0.075, 0.0375004,],  [  0.0500002, 0.0749999, 0.0749993,],  [  -0.0124989, -0.0750003, -0.0500011,],  [  0.0687494, -0.0499996, 0.0906254,], ],
    [ [  -0.103584, -0.0656152, -0.0108447,],  [  -0.0401657, 2.38419e-07, -0.017189,],  [  0.0125008, 0.0749998, 0.0437489,],  [  -0.0999997, 0.0499998, 0.0562497,],  [  -0.0374999, -0.1, 0.0999999,],  [  0.0374999, 0.125, -0.0749993,],  [  -0.0124998, -0.0749994, -0.0562503,],  [  0.04375, 0.0749996, 0.0531263,], ],
    [ [  -0.0437498, 0.0501465, -0.0703173,],  [  0.0124998, 0.0499998, 0.0596095,],  [  0.0749989, 0.075, 0.0749998,],  [  0.0125008, 0.125, -0.0312505,],  [  0.0125003, -0.0999998, 0.0374999,],  [  -0.0412501, 0.1, -0.058125,],  [  0.0162497, 0.0249996, 0.0374997,],  [  -0.0437498,0.0750004, -0.0781249,], ],
    [ [  0.093751, -0.0995312, 0.0562482,],  [  0.0750003, 0.09375, -0.0656242,],  [  -0.0375013, 0.11875, -0.0593748,],  [  0.0374997, 0.0687504, 0.0593751,],  [  -0.0375, -0.0687499, 0.10125,],  [  0.0374999, -0.09375, -0.04,],  [  -0.0374999, 0.11875, -0.0612497,],  [  0.06875, -0.0687504, -0.1,], ],
))

v1 = v_hat - q + sym_grad(eta1)

# print(np.array(v1 - answer) < 1.0e-4)


In [196]:
# calc_error

pix_error = (v1 - v_hat) * (v1 - v_hat)
error = np.sum(pix_error[:, :, 0]) + np.sum(pix_error[:, :, 1]) + 2 * np.sum(pix_error[:, :, 2])

print(error)


280.519950866


In [202]:
# calc_u

answer_tmp = np.array((
    [ [  0.5675,],  [  0.520003,],  [  0.243747,],  [  0.193752,],  [  1.04,],  [  0.755,],  [  0.0143753,],  [  1.705,], ],
    [ [  0.431251,],  [  1.275,],  [  1.85125,],  [  0.999996,],  [  1.4375,],  [  0.0662525,],  [  1.88875,],  [  0.429376,], ],
    [ [  0.688748,],  [  0.126253,],  [  0.348747,],  [  0.015005,],  [  0.29,],  [  0.244996,],  [  0.155003,],  [  0.4425,], ],
    [ [  -0.0811646,],  [  0.647413,],  [  1.38125,],  [  0.894998,],  [  0.0175004,],  [  1.56,],  [  1.87,],  [  2.15375,], ],
    [ [  1.00908,],  [  3.68505,],  [  0.575148,],  [  0.982498,],  [  3.32125,],  [  1.055,],  [  0.256251,],  [  0.10125,], ],
    [ [  0.21173,],  [  -0.311456,],  [  0.828213,],  [  0.556251,],  [  1.77,],  [  1.50688,],  [  -0.0318736,],  [  1.94875,], ],
    [ [  0.326353,],  [  1.39735,],  [  1.67914,],  [  0.938752,],  [  0.500001,],  [  1.95625,],  [  2.91562,],  [  1.66563,], ],
    [ [  3.73712,],  [  0.77477,],  [  -0.102503,],  [  0.909376,],  [  -0.0112494,],  [  0.461874,],  [  0.544377,],  [  0.531874,], ],
))

answer = np.zeros((answer_tmp.shape[0], answer_tmp.shape[1]))
answer[:, :] = answer_tmp[:, :, 0]

# print(np.abs(ans_v1 - v1) < 1.0e-3)

u = input - square_div(v1)

# print(input)
# print(v1)

print(np.abs(answer - u) < 1.0e-5)



[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]
